### PR TITLE
Assignment 2.2

### PR DESCRIPTION
**Pull request by ltm22**
CSS Styling Sheet (Styles.css)
HTML file (csspage.html)
image for formatting ('image of jesus.jpg')
image for background formatting (dog_with_bone.jpg)
A bevy of Font Awesome files to ensure Icons work.

### CODE REVIEW

**Comment by ltm22** [comment]
@pastorsj Due to the need to include a whole directory from Font Awesome, it may take a few minutes for the commit review page to load. The first file that appears, 'csspage.html', is the html file as you might expect. The very bottom file, 'Styles.css', is my personal styling sheet. Therefore, it may make sense to open this page and return five minutes later once all the binary files in between are processed and loaded on the webpage.

I would not have pushed so many files save for the need for the icons in the webpage... perhaps we can discuss during class if I misunderstand and should only push the two files, regardless of their dependencies?

**Comment by pastorsj** [comment]
@ltm22 Please use a cdn rather than include all of font awesome. You can find a tutorial here for that. https://www.w3schools.com/icons/fontawesome_icons_intro.asp

**Comment by ltm22** [comment]
@pastorsj Thanks for the reference. This is what I was trying to work out earlier today when I dropped a note in the discussion and on the GroupMe. I've pushed again, but this time removing all of the binary FA files and updating the html document to reflect this proper stylesheet reference in the head. Please let me know in case of any other trouble reviewing.

If it is still uncomfortable, we can reject the pull request altogether and I can re-instantiate with just the two files this time. Just let me know?

**Comment by ltm22** [comment]
@paulbohman I saw your comments and have updated the html file per your suggestions. See the newest commit, thanks!!

**Review by paulbohman — APPROVED** [review]

**Pull request merged**
